name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [mavlink-service, mqtt-eon-service, ota-update-service] # add all your services here

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}   # adjust path for each service folder
          file: ./services/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
            ${{ secrets.DOCKERHUB_TOKEN }}/${{ matrix.service }}:${{ github.sha }}
