name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKER_PASSWORD  }}

      - name: Parse docker-compose for services
        id: parse
        run: |
                services=$(yq e '.services | keys | .[]' docker-compose.yml | xargs)
                echo "services=$services" >> $GITHUB_OUTPUT

      - name: Build and Push Images
        run: |
          VERSION=$(yq e '.version' docker-compose.yml || echo "latest")
          for service in ${{ steps.services.outputs.services }}; do
            echo "🔨 Building service: $service"
            IMAGE="vesudarsan/${service}:${VERSION}"
            docker build -t $IMAGE ./$service
            docker push $IMAGE
          done         