name: Build and Push Docker Images

on:
  push:
    branches:
      - main   # or master, whichever your repo uses

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push all Docker images
        run: |
          USERNAME="vesudarsan"

          # Loop through each folder with a Dockerfile
          for service in $(find . -maxdepth 2 -type f -iname "Dockerfile" -exec dirname {} \;); do
            SERVICE_NAME=$(basename "$service" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
            
            echo "🚀 Building and pushing $SERVICE_NAME"

            docker buildx build \
              --platform linux/amd64 \
              --push \
              -t $USERNAME/$SERVICE_NAME:latest \
              -t $USERNAME/$SERVICE_NAME:${{ github.sha }} \
              "$service"
          done
