name: Build and Push Docker Images

on:
  push:
    branches:
      - main   # or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push all Docker images
        run: |
          USERNAME=$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          
          echo "🔍 Looking for Dockerfiles..."
          for service in $(find . -maxdepth 2 -type f -iname "Dockerfile" -exec dirname {} \;); do
            SERVICE_NAME=$(basename "$service" | tr '[:upper:]' '[:lower:]')
            
            echo "🚀 Building $SERVICE_NAME"
            
            docker buildx build \
              --platform linux/amd64 \
              --push \
              -t $USERNAME/$SERVICE_NAME:latest \
              -t $USERNAME/$SERVICE_NAME:${{ github.sha }} \
              "$service"
          done
